---
title: "Referências"
---

ARRUDA, José Jobson de Andrade. **A Revolução Inglesa**.São Paulo: Brasiliense, 1988.

ÁVILA, María Elena *et al.* Victimization, perception of insecurity, and changes in daily routines in Mexico. **Revista de Saúde Pública**, \[*S. l.*\], v. 50, n. 60, 2016.

BABBIE, Earl. **Métodos de pesquisas de survey**. Belo Horizonte: Editora UFMG, 2003.

BARLOW, David H. **Anxiety and its disorders**: The nature and treatment of anxiety and panic. New York: Guilford Press, 2004.

BAUMAN, Zygmunt. **Comunidade**: a busca por segurança no mundo atual. Tradução Plínio Dentzien. Rio de Janeiro: Zahar, 2003.

BAUMAN, Zygmunt. **Confiança e medo na cidade**. Tradução de Eliana Aguiar. Rio de Janeiro: Zahar, 2009.

BAUMAN, Zygmunt. **Medo líquido**. Tradução de Carlos Alberto Medeiros. Rio de Janeiro: Zahar, 2008.

BAUMAN, Zygmunt; LYON, David. **Vigilância líquida**. Tradução de Carlos Alberto Medeiros. Rio de Janeiro: Zahar, 2013.

BECK, Ulrich. **La sociedad del riesgo global**: en busca de la seguridad perdida. Tradução de Rosa S. Carbó. Madrid: Paidós, 2008.

BECK, Ulrich. **Sociedade de risco mundial**: em busca da segurança perdida. Tradução de Marian Toldy e Teresa Toldy. Lisboa: Edições 70, 2016.

BECK, Ulrich. **Sociedade de risco**: rumo a uma outra modernidade. Tradução de Sebastião Nascimento. São Paulo: Editora 34, 2011.

BLANCO, Luisa; RUIZ, Isabel. The Impact of Crime and Insecurity on Trust in Democracy and Institutions. **American Economic Review**: Papers & Proceedings, \[*S. l.*\], v. 103, n. 3, p. 284-288, 2013.

BORGES, Doriam; CANO, Ignácio. Determinantes do medo do crime no Brasil: o efeito da coesão social. **Civitas**: Revista de Ciências Sociais, Rio de Janeiro, v. 21, n. 3, p. 455-466, 2021.  Disponível em: https://revistaseletronicas.pucrs.br/civitas/article/view/35603. Acesso em: 8 out. 2024.

BOX, George E. P.; COX, David R. An Analysis of Transformations. **Journal of the Royal Statistical Society Series B**: Statistical Methodology, \[*S. l.*\], v. 26, n. 2, p. 211-243, 1964.

CARDOSO, Gabriela Ribeiro. **Vitimização, medo do crime e legitimidade democrática na América Latina**: mecanismos causais e efeitos contextuais em perspectiva. 2021. Tese (Doutorado em Sociologia e Ciência Política) – Programa de Pós-Graduação em Sociologia e Ciência Política, Universidade Federal de Santa Catarina, Florianópolis, 2021. Disponível em: https://repositorio.ufsc.br/handle/123456789/234600. Acesso em: 8 out. 2024.

CARDOSO, Gabriela Ribeiro; BORBA, Julian. Violência e legitimidade democrática: um balanço da literatura sobre o contexto latino-americano. **Sociedade e Estado**, \[*S. l.*\], v. 38, n. 1, p. 193-210, jan./abr. 2023. Disponível em: https://periodicos.unb.br/index.php/sociedade/article/view/43495. Acesso em: 8 out. 2024.

CASTEL, Robert. **A insegurança social**: o que é ser protegido? Tradução de Lúcia M. Endlich Orth. Petrópolis: Vozes, 2005.

CASTEL, Robert. **As metamorfoses da questão social**: uma crônica do salário. Tradução de Iraci D. Poleti. Petrópolis: Vozes, 1998.

CENTRO DE ESTUDOS DE CRIMINALIDADE E SEGURANÇA PÚBLICA. **Percepção de medo no estado de Minas Gerais**. Belo Horizonte: UFMG, 2008.

CERQUEIRA, Daniel; LOBÃO, Waldir. Determinantes da criminalidade: arcabouços teóricos e resultados empíricos. **DADOS**: Revista de Ciências Sociais, Rio de Janeiro, v. 47, n. 2, p. 233-269, 2004.

CHADEE, Derek A.; VIRGIL, Nikiesha J.; DITTON, Jason. State-trait anxiety and fear of crime: a social psychological perspective. *In:* LEE, Murray; FARRALL, Stephen. **Fear of crime**: Critical voices in an age of anxiety. Oxon: Routledge-Cavendish, 2008. p. 168-187.

CHEIN, Flávia. **Introdução aos modelos de regressão linear**: um passo inicial para compreensão da econometria como uma ferramenta de avaliação de políticas públicas. Brasília: Enap, 2019. Disponível em: https://repositorio.enap.gov.br/handle/1/4788. Acesso em: 9 out. 2024.

CLARKE, Steve. Trends in crime and criminal justice, 2010: Decreases in recorded crime except for domestic burglary. **Statistics in Focus**,\[*S. l.*\], v. 18, 2013. Disponível em: https://ec.europa.eu/eurostat/web/products-statistics-in-focus/-/ks-sf-13-018. Acesso em: 9 out. 2024.

COLLINS, Rachael E. Addressing the inconsistencies in fear of crime research: a meta-analytic review. **Journal of Criminal Justice**, \[*S. l.*\], v. 47, p. 21-31, 2016.

COSTA, Arthur Trindade M.; DURANTE, Marcelo Ottoni. Medo do crime, desordens e coesão social no Distrito Federal. **Sociedade e Estado**, \[*S. l.*\], v. 36, n. 2, p. 613-637, maio/ago. 2021. Disponível em: https://periodicos.unb.br/index.php/sociedade/article/view/34151. Acesso em: 9 out. 2024.

DAMMERT, Lucía. **Fear and crime in Latin America**: redefining state-society relations. New York: Routledge, 2012.

DAMMERT, Lucía; MALONE, Mary Fran T. Fear of crime or fear of life? Public insecurities in Chile. **Bulletin of Latin American Research**, \[*S. l.*\], v. 22, n. 1, p. 79-101, 2003.

DAMMERT, Lucía; TOBAR, Felipe Salazar. Fear and insecurity in Latin America.*In:* LEE, Murray; MYTHEN, Gabe (ed.). **The Routledge International Handbook on Fear of Crime**. London: Routledge: 2017. p. 339-353.

DELUMEAU, Jean. **História do medo no Ocidente, 1300-1800**: uma cidade sitiada. São Paulo: Companhia das Letras, 2009.

ESTADOS UNIDOS. President's Commission on Law Enforcement and Administration of Justice. **The Challenge of Crime In a Free Society**: A Report by the President's Commission on Law Enforcement and Administration of Justice. Washington: United State Government Printing Office, 1967.

FARRALL, Stephen *et al.* Questioning the measurement of the ‘fear of crime’: findings from a major methodological study. **The British Journal of Criminology**, \[*S. l.*\], v. 37, n. 4, p. 658-679, 1997.

FARRALL, Stephen; GRAY, Emily; JACKSON, Jonathan. Theorising the fear of crime: the cultural and social significance of insecurities about crime. **Experience & Expression in the Fear of Crime Working Paper**, \[*S. l.*\], n. 5, 2007.

FÁVERO, Luiz Paulo; BELFIORE, Patrícia. **Manual de análise de dados**: estatística e modelagem multivariada com Excel®, SPSS® e Stata®.Rio de Janeiro: LTC, 2022.

FIGUEIREDO FILHO, Dalson Britto *et al.* Análise fatorial garantida ou o seu dinheiro de volta: uma introdução à redução de dados. **Revista Eletrônica de Ciência Política**, \[*S. l.*\], v. 5, n. 2, 2014. Disponível em: https://revistas.ufpr.br/politica/article/view/40368. Acesso em: 9 out. 2024.

FIGUEIREDO FILHO, Dalson Britto; SILVA JÚNIOR, José Alexandre da. Visão além do alcance: uma introdução à análise fatorial. **Opinião Pública**, Campinas, v. 16, n. 1, p. 160-185, jun. 2010.

GAROFALO, James. Victimization and the fear of crime. **Journal of Research on Crime and Delinquency**, v. 16, n. 1, p. 80-97, 1979.

GELVEZ-FERREIRA, Juan David. ¿Cuáles determinantes se relacionan con la percepción de inseguridad? Un análisis estadístico y espacial para la ciudad de Bogotá, D. C. **Revista Criminalidad**,Bogotá, v. 61, n. 1, p. 69-84, enero/abr. 2018. Disponível em: https://revistacriminalidad.policia.gov.co:8000/index.php/revcriminalidad/article/view/49. Acesso em: 9 out. 2024.

GIDDENS, Anthony. **A constituição da sociedade**. 3. ed. Tradução de Álvaro Cabral. São Paulo: Martins Fontes, 2009.

GIDDENS, Anthony. **Modernidade e identidade**. Tradução de Plínio Dentzien. Rio de Janeiro: Zahar, 2002.

GODFREY, Barry. Fear of crime before ‘fear of crime?’. *In:* LEE, Murray; MYTHEN, Gabe (ed.). **The Routledge International Handbook on Fear of Crime**. London: Routledge: 2017. p. 7-19.

GOUSETI, Ioanna. A construal-level approach to the fear of crime. *In:* LEE, Murray; MYTHEN, Gabe (ed.). **The Routledge International Handbook on Fear of Crime**. London: Routledge: 2017. p. 137-154.

GRAY, Emily; JACKSON, Jonathan; FARRAL, Stephen. Feelings and functions in the fear of crime: applying a new approach to victimisation insecurity. **British Journal of criminology***,* \[*S. l.*\], v. 51, p. 75-94, 2010. Disponível em: https://academic.oup.com/bjc/article/51/1/75/344837. Acesso em: 9 out. 2024.

GRAY, Emily; JACKSON, Jonathan; FARRALL, Stephen. Reassessing the fear of crime. **European Journal of Criminology**, v. 5, n. 3, p. 363-380, 2008.

HAIR, Joseph F. *et al.* **Análise multivariada de dados**. Porto Alegre: Bookman, 2009.

HALE, Chris. Fear of crime: a review of the literature. **International Review of Victimology**, \[*S. l.*\], v. 4, n. 2, p. 79-150, 1996.

HERNÁNDEZ, Wilson. Costos sociales de la victimización en América Latina: Percepción de inseguridad, capital social y percepción de la democracia. **Latin American Research Review**, \[*S. l.*\], v. 54, n. 4, p. 835-853, 2019.

HINKLE, Joshua C.; WEISBURD, David. The irony of broken windows policing: A micro-place study of the relationship between disorder, focused police crackdowns and fear of crime. **Journal of Criminal justice**, \[*S. l.*\], v. 36, n. 6, p. 503-512, 2008.

HOUGH, Mike. Worry about crime: mental events or mental states? **International Journal of Social Research Methodology**, \[*S. l.*\], v. 7, n. 2, p. 173-176, 2004.

INSTITUTO BRASILEIRO DE GEOGRAFIA E ESTATÍSTICA. Pesquisa Nacional por Amostra e Domicílios. **Características da vitimização e do acesso à justiça no Brasil**: 2009. Rio de Janeiro: IBGE, 2010. Disponível em: https://bibliotecadigital.economia.gov.br/handle/123456789/301. Acesso em: 9 out. 2024.

INSTITUTO BRASILEIRO DE GEOGRAFIA E ESTATÍSTICA. **Pesquisa Nacional por Amostra de Domicílios Contínua Anual - PNADC/A**. Rio de Janeiro: IBGE, 2021. Disponível em: https://sidra.ibge.gov.br/pesquisa/pnadca/tabelas. Acesso em: 11 out. 2024.

JACKSON, Jonathan. A psychological perspective on vulnerability in the fear of crime. **Psychology, Crime & Law**, \[*S. l.*\], v. 15, n. 4, p. 365-390, 2009.

JACKSON, Jonathan; GRAY, Emily; FARRALL, Stephen. Untangling the fear of crime. **Criminal Justice Matters**, \[*S. l.*\], v. 75, n. 1, p. 12-13, 2009.

JARRETT-LUCK, Madeleine. **Reconceptualising Fear of Crime**: Emergence of Crime Awareness. 2017. Thesis (Doctoral) – Bond University, Queensland, Australia, 2017. Disponível em: https://research.bond.edu.au/en/studentTheses/reconceptualising-fear-of-crime-emergence-of-crime-awareness. Acesso em: 9 out. 2024.

JING, Feng *et al.* How does crime-specific victimization impact fear of crime in urban China? The role of neighborhood characteristics. **International Journal of Offender Therapy and Comparative Criminology**, \[*S. l.*\], v. 68, n. 5, p. 540-565, 2024.

KESSLER, Gabriel. **El sentimiento de inseguridad**: sociologia del temor al delito*.* Buenos Aires: Siglo XXI Editores, 2009.

KLINE, Rex B. **Principles and practice of structural equation modeling**. 5. ed. New York: Guilford Publications, 2023.

LEE, Murray. **Inventing Fear of Crime**: Criminology and the Politics of Anxiety. Cullompton: Willan Publishing. 2007.

LEE, Murray. The enumeration of anxiety: power, knowledge and fear of crime. *In:* LEE, Murray; FARRALL, Stephen. **Fear of crime**: Critical voices in an age of anxiety. Oxon: Routledge-Cavendish, 2008. p. 44-56.

LEE, Murray. The genesis of ‘fear of crime’. **Theoretical Criminology**, \[*S. l.*\], v. 5, n. 4, p. 467-485, 2001.

LEE, Murray; FARRALL, Stephen. Critical voices in an age of anxiety: Ending with the identification of where to begin. *In:* LEE, Murray; FARRALL, Stephen. **Fear of crime**: Critical voices in an age of anxiety. Oxon: Routledge-Cavendish, 2008. p. 223-226.

LEE, Murray; FARRALL, Stephen. **Fear of crime**: Critical voices in an age of anxiety. Oxon: Routledge-Cavendish, 2008.

LEE, Murray; MYTHEN, Gabe (ed.). **The Routledge international handbook on fear of crime.** Nueva York: Routledge, 2018.

LIMA, Renato Sérgio de *et al.* Medo da violência e adesão ao autoritarismo no Brasil: proposta metodológica e resultados em 2017. **Opinião pública**, Campinas, v. 26, n. 1, p. 34-65, 2020. Disponível em: https://www.cesop.unicamp.br/por/opiniao_publica/artigo/644. Acesso em: 9 out. 2024.

LOO, Dennis. The moral panic that wasn’t: The sixties crime issue in the US. *In:* LEE, Murray; FARRALL, Stephen. **Fear of crime**: Critical voices in an age of anxiety. Oxon: Routledge-Cavendish, 2008. p. 24-43.

MATOS, Daniel Abud Seabra; RODRIGUES, Erica Castilho. **Análise fatorial**. Brasília: Enap, 2019. Disponível em: https://repositorio.enap.gov.br/handle/1/4790. Acesso em: 9 out. 2024.

MEDINA-DURANGO, Carlos Alberto; TAMAYO-CASTAÑO, Jorge Andrés. An assessment of how urban crime and victimization affects life satisfaction. **Borradores de Economía**, Bogotá, n. 640, p. 2-37, 2011. Disponível em: https://repositorio.banrep.gov.co/server/api/core/bitstreams/c75e0941-204d-4752-87bc-9053cce23dd0/content. Acesso em: 9 out. 2024.

MONTEIRO, Felipe Mattos. **A produção social e política dos homicídios**: uma análise macrossocial da trajetória das taxas de homicídios em Santa Catarina (1992 a 2017). 2019. Tese (Doutorado em Sociologia) – Universidade de São Paulo, São Paulo, 2019. Disponível em: https://www.teses.usp.br/teses/disponiveis/8/8132/tde-25102019-185349/pt-br.php. Acesso em: 9 out. 2024.

MONTEIRO, Felipe Mattos.Novas perspectivas sobre os estudos das tendências de homicídios: uma análise das trajetórias latentes das taxas de homicídios no estado de Santa Catarina–Brasil. **Criminological Encounters**, \[*S. l.*\], v. 4, n. 1, p. 89-114, 2021. Disponível em: https://www.criminologicalencounters.org/index.php/crimenc/article/view/77. Acesso em: 9 out. 2024.

MYTHEN, Gabe; LEE, Murray. Conclusion: Advancing fear of crime? Emergent themes and new directions. *In:* LEE, Murray; MYTHEN, Gabe (ed.). **The Routledge international handbook on fear of crime**. Nueva York: Routledge, 2018. p. 484-490.

NATAL, Ariadne; OLIVEIRA, André Rodrigues de. Medo do crime: mensurando o fenômeno e explorando seus preditores na cidade de São Paulo. **Opinião Pública**, Campinas, v. 27, n. 3, p. 757-796, 2021.  Disponível em: https://periodicos.sbu.unicamp.br/ojs/index.php/op/article/view/8668734. Acesso em: 18 ago. 2024.

NEVES, Jorge Alexandre Barbosa. **Modelo de equações estruturais**: uma introdução aplicada*.* Brasília: Enap, 2018. Disponível em: https://repositorio.enap.gov.br/handle/1/3334. Acesso em: 9 out. 2024.

NÓBREGA JR, José Maria. Teorias do crime e da violência: uma revisão da literatura. **BIB**: Revista Brasileira de Informação Bibliográfica em Ciências Sociais, São Paulo, n. 77, p. 69-89, 2014. Disponível em: https://bibanpocs.emnuvens.com.br/revista/article/view/391. Acesso em: 9 out. 2024.

PAIN, Rachel. Place, social relations and the fear of crime: a review. **Progress in human geography**, \[*S. l.*\], v. 24, n. 3, p. 365-387, 2000.

PERKINS, Douglas D.; TAYLOR, Ralph B. Ecological assessments of community disorder: Their relationship to fear of crime and theoretical implications. **American journal of community psychology**, \[*S. l.*\], v. 24, n. 1, p. 63-107, 1996.

RADDER, Nicole E. The threat of victimization: a theoretical reconceptualization of fear of crime. **Sociological Spectrum**, \[*S. l.*\], v. 24, n. 6, p. 689-704, 2004.

RADDER, Nicole E.; MAY, David C.; GOODRUM, Sarah. An empirical assessment of the “threat of victimization”: considering fear of crime, perceived risk, avoidance, and defensive behaviors. **Sociological Spectrum**: Mid-South Sociological Association, \[*S. l.*\], v. 27, n. 5, p. 475-505, 2007.

RIBEIRO, Allan Kássio de Oliveira Santos. **A sensação de insegurança na vizinhança da população do Distrito Federal entre 2015 e 2018**. 2020. Dissertação (Mestrado em Sociologia) – Programa de Pós-Graduação em Sociologia, Universidade de Brasília, Brasília, 2020. Disponível em: https://www.realp.unb.br/jspui/handle/10482/37955. Acesso em: 9 out. 2024.

RODRIGUES, Corinne Davis; OLIVEIRA, Valéria Cristina de. Medo de crime, integração social e desordem: uma análise da sensação de insegurança e do risco percebido na capital de Minas Gerais. **Revista Teoria & Sociedade**, \[*S. l.*\], v. 20, n. 2, p. 156-184, 2012. Disponível em: https://bib44.fafich.ufmg.br/index.php/rts/article/view/62. Acesso em: 9 out. 2024.

ROLIM, Marcos. Pesquisas de vitimização, instrumentos fundamentais para a segurança pública. *In:* SEIBEL, Erni J.; HARTMAN, Fábio Cadore (org.). **Vitimização e sentimento de insegurança**: metodologias e pesquisa. Curitiba: Brazil Publishing, 2019. p. 11-31.

ROLIM, Marcos.Relatório da Primeira Pesquisa de Vitimização de Porto Alegre. **IPO**: Instituto Pesquisas de Opinião, \[*S. l.*\], 2 fev. 2018. Disponível em: https://www.ipo.inf.br/primeira-pesquisa-de-vitimizacao-de-porto-alegre/. Acesso em: 9 out. 2024.

ROUNTREE, Pamela Wilcox; LAND, Kenneth C. Perceived risk versus fear of crime: Empirical evidence of conceptually distinct reactions in survey data. **Social forces**, \[*S. l.*\], v. 74, n. 4, p. 1353-1376, 1996.

SAMPSON, Robert J.; GROVES, Beverly. Community structure and crime: testing social disorganization theory. **American Journal of Sociology**, \[*S. l.*\], v. 94, n. 4, p. 774-802, Jan. 1989.

SAMPSON, Robert J.; RAUDENBUSH, Stephen W.; EARLS, Felton. Neighborhoods and violent crime: a multilevel study of collective efficacy. **Science**, \[*S. l.*\], v. 15, n. 277, p. 918-924, 1997.

SAMPSON, Robert J.; RAUNDENBUSH, Stephen W. Seeing disorder: neighborhood stigma and the social construction of “broken windows”. **Social Psychology Quarterly**, \[*S. l.*\], v. 67, n. 4, p. 319-342, 2004.

SANTOS JÚNIOR, Aldo Antônio dos; DUTRA, Luis Henrique; SILVA FILHO, Daniel Bernardo da. Levantamento da percepção do medo e do crime em Santa Catarina. **Revista Brasileira de Segurança Pública**, \[*S. l.*\], v. 1, n. 2, p. 94-119, 2007. Disponível em: https://revista.forumseguranca.org.br/rbsp/article/view/19. Acesso em: 9 out. 2024.

SCARBOROUGH, Brittney K. *et al.* Assessing the relationship between individual characteristics, neighborhood context, and fear of crime. **Journal of Criminal Justice**, \[*S. l.*\], v. 38, n. 4, p. 819-826, 2010.

SEIBEL, Erni J.; HARTMAN, Fábio Cadore (org.). **Vitimização e sentimento de insegurança**: metodologias e pesquisa. Curitiba: Brazil Publishing, 2019.

SENNETT, Richard. **A cultura do novo capitalismo**. Tradução de Clóvis Marques. Rio de Janeiro: Record, 2008.

SILVA, Bráulio Figueiredo Alves da; BEATO FILHO, Claudio Chaves. Ecologia social do medo: avaliando a associação entre contexto de bairro e medo de crime. **Revista Brasileira de Estudos de População**, Rio de Janeiro, v. 30, p. S155-S170, 2013.

SKOGAN, Wesley G. Disorder and crime. *In:* FARRINGTON, David P.; WELSH, Brandon C. (ed.). **The Oxford handbook of crime prevention**. Oxford: Oxford University Press, 2012. *E-book*. p. 173-188.

SOARES, Gláucio Ary Dillon. A sensação de insegurança: teorias, hipóteses e dados. *In:* DUARTE, Mário Sérgio de Brito (coord.). **Pesquisa de condições de vida e vitimização de 2007**. Rio de Janeiro: Riosegurança, 2008. p. 108-125.

STAFFORD, Mai; CHANDOLA, Tarani; MARMOT, Michael. Association between fear of crime and mental health and physical functioning. **American journal of public health**, \[*S. l.*\], v. 97, n. 11, p. 2076-2081, Nov. 2007.

STEIN, Rachel E. Neighborhood residents’ fear of crime: a tale of three cities. *Sociological* **Focus**, \[*S. l.*\], v. 47, n. 2, p. 121-139, 2014.  Disponível em: http://www.jstor.org/stable/24579304. Acesso em: 6 maio 2024.

TRINDADE, Arthur; DURANTE, Marcelo. Medo do crime e vitimização no Distrito Federal: analisando as vulnerabilidades de gênero, idade, raça e renda. **Dilemas**: Revista de Estudos de Conflito e Controle Social,Rio de Janeiro, v. 12, n. 2, p. 239-265, maio/ago. 2019. Disponível em: https://revistas.ufrj.br/index.php/dilemas/article/view/17794. Acesso em: 9 out. 2024.

VALENTE, Riccardo. Vulnerabilidad social, déficits urbanísticos y violencia letal: una aproximación cuantitativa al auge de homicidios en Florianópolis (2011-2017). *In:* SEIBEL, Erni J.; HARTMAN, Fábio Cadore (org.). **Vitimização e sentimento de insegurança**: metodologias e pesquisa. Curitiba: Brazil Publishing, 2019. p. 33-60.

VALENTE, Riccardo; CRESCENZI LANNA, Lucrezia; CHAINEY, Spencer. Participatory design of a thematic questionnaire in the field of victimization studies. **European Journal of Criminology**, \[*S. l.*\], v. 16, n. 2, p. 170-187, 2019.

VALENTE, Riccardo; PERTEGAS, Sergi Valera. Ontological insecurity and subjective feelings of unsafety: Analysing socially constructed fears in Italy. **Social Science Research**, \[*S. l.*\], v. 71, p. 160-170, 2018.

VALENTE, Riccardo; PERTEGAS, Sergi Valera; OLMOS, Joan Guardia. A structural equation model estimation of the role of social vulnerability as a predictor of people’s feelings of unsafety. **Social Indicators Research**, \[*S. l.*\], v. 143, n. 2, p. 433-449, 2019.

VANDERVEEN, G. **Interpreting fear, crime, risk and unsafety**: Conceptualisation and measurement.Den Haag: Boom Juridische Uitgevers, 2006.

VIENO, Alessio; ROCCATO, Michele; RUSSO, Silvia. Is fear of crime mainly social and economic insecurity in disguise? A multilevel multinational analysis. **Journal of Community & Applied Social Psychology**, \[*S. l.*\], v. 23, n. 6, p. 519-535, 2013.

WACQUANT, Löic. **As prisões da miséria**. Tradução de André Telles. Rio de Janeiro: Zahar, 2001.

WACQUANT, Löic. Crafting the neoliberal state Workfare, prisonfare and social insecurity. **Sociologie Românească**, \[*S. l.*\], v. 8, n. 3, p. 5-23, 2010.

WACQUANT, Löic. **Punir os pobres**: a nova gestão da miséria nos Estados Unidos. Tradução de Sérgio Lamarão. Rio de Janeiro: Revan, 2003.

WARR, Mark. Fear of crime in the United States: Avenues for research and policy. **Criminal Justice**, \[*S. l.*\], v. 4, n. 4, p. 451-489, 2000.

WEBER, Leanne; LEE, Murray. Preventing indeterminate threats: Fear, terror and the politics of preemption. *In:* LEE, Murray; FARRALL, Stephen. **Fear of crime**: Critical voices in an age of anxiety. Oxon: Routledge-Cavendish, 2008. p. 71-93.

WILSON, James Quinn.; KELLING, George L. Broken Windows: the police and neighbourhood safety. **The Atlantic Monthly**,\[*S. l.*\],p. 29-38, mar. 1982.
