---
title: "Conclusão"
---

Este estudo voltou-se à análise dos determinantes do medo do crime de uma amostra da população de Florianópolis/SC, integrando à pesquisa elementos sociológicos que ampliam o escopo de abordagem sobre as causas e influências sociais do medo do crime. A tese envolveu verificar a relevância de se integrar aos estudos do medo variáveis explicativas que dizem respeito a um tipo específico de insegurança. Esta, operacionalizada enquanto uma vulnerabilidade social, a qual exerce influência direta e indireta sobre o medo através da possível combinação com outros elementos sociais que também o afetam, e são amplamente mensurados em estudos anteriores.

Em tese, defende-se que fatores como a vitimização criminal, desordens e incivilidades, laços sociais precários e marcadores de vulnerabilidades sociodemográficas como idade, cor/raça e sexo, são capazes de explicar os movimentos do medo do crime em grande medida. No entanto, elementos de uma insegurança social dispersa, caracterizada pela autopercepção de não pertencimento e de exclusão social, assim como, pela presença de uma ansiedade difusa sobre as condições pessoais de saúde e financeira no futuro breve, vão exercer impactos diretos e indiretos sobre o medo do crime. Com a tese subjacente de quea insegurança social importa aos estudos do MDC, procurou-se testar e mensurar os múltiplos determinantes do medo ao mesmo tempo, ao passo em que se verificou aspectos sociais que, quando combinados à insegurança social, têm a capacidade de ampliar e/ou de reduzir seus efeitos sobre o medo.

Para isso, o estudo envolveu a realização de um *survey* no município de Florianópolis, em 2019, o qual contou com um total de 626 entrevistas em sua base de dados final. Para as análises utilizou-se técnicas multivariadas de análise fatorial por componentes principais, regressão linear múltipla e modelagem de equações estruturais. Além da hipótese subjacente de que a insegurança social importa aos estudos do MDC, a tese envolveu testar algumas hipóteses que dizem respeito à magnitude e significância das tradicionais medidas explicativas do medo, adicionando a insegurança social. Também testou-se caminhos hipotéticos, teoricamente embasados, pelos quais a insegurança percorre e se atrela a outros determinantes do medo do crime, criando efeitos indiretos que intensificam ou neutralizam a força da insegurança sobre o medo, para além de seu impacto direto.

De maneira geral, todas as análises corroboram a hipótese subjacente que a insegurança social, tal como caracterizada nesta tese, é um elemento relevante aos estudos do medo do crime. As evidências fornecidas pelos resultados demonstram a capacidade preditiva da insegurança social sobre o medo, e sobre aspectos ambientais ligados às condições em nível de vizinhança. Fatores ambientais são tradicionalmente estudados em relação ao MDC, e neste estudo mostraram-se especialmente importantes devido à sua capacidade de influenciar as percepções de medo do crime da amostra.

Teoricamente, tem-se que o contato cotidiano com desordens e incivilidades no bairro onde se vive leva a uma elevação do medo. Locais abandonados, com lixo e sujeira, precários em serviços e estrutura pública, com pessoas praticando crimes e contravenções, brigando e fazendo barulho, levam a um aumento do medo do crime. Nossos resultados confirmam estes pressupostos. Ainda em contexto de bairro, boas relações de vizinhança, com laços sociais de confiança e apoio, ligadas à satisfação de morar no bairro são capazes de predizer a redução do medo, porém em baixa intensidade, tal como foi teoricamente previsto.

Além disso, a vitimização pessoal e/ou de um próximo também elevam o medo, reforçando achados de pesquisas antigos e recentes que apontam para os efeitos de eventos criminais na vida das pessoas. Assim como algumas características sociodemográficas de cor/raça, sexo e idade, as quais são preditores de diferentes dimensões do medo do crime. Estes marcadores caracterizam vulnerabilidades sociodemográficas, ligadas à ideia de probabilidade (maior) em determinados perfis sentirem medo do crime. Sexo/gênero, idade e, em menor intensidade cor/raça, mostraram-se preditores relevantes do medo, tal como previsto na literatura. O efeito de cor/raça foi inesperado, pois observou-se um efeito quase insignificante em magnitude, e em sentido negativo, como se a cor da pele (não-branca) levasse à redução do medo, em termos de grau de segurança ao andar sozinho (a) no bairro à noite.

Entretanto, a tese previu efeitos de um tipo de insegurança social que trouxe aspectos de vulnerabilidades e ansiedades socialmente produzidas, os quais ampliam a compreensão dos efeitos dos preditores mais utilizados nas abordagens ao medo do crime. A insegurança social, operacionalizada pela percepção de desprezo social e ansiedade sobre o futuro, afeta o medo do crime de maneira positiva, como se cada grau de elevação no nível de insegurança resultasse em um aumento de nível do medo. No entanto, mais instigante foi a constatação de que quando a insegurança social se relaciona com problemas em contexto de bairro, ela é ampliada e acarreta um efeito um pouco maior ao medo que seu efeito direto. Por outro lado, nos casos em que a insegurança se encontra com elementos de coesão social no bairro, seu efeito sobre o medo é quase totalmente neutralizado.

Esses achados reforçam argumentos presentes na literatura, e também trazem novas explicações sobre o fenômeno do MDC. Primeiro, a covariância negativa entre dois elementos explicativos contextuais do medo, desorganização e coesão social, os quais atuam em sentido contrário quando em relação ao medo, sendo que o peso da desorganização social é muito mais impactante. A coesão produz um efeito negativo sobre o medo, mas com intensidade baixa, e este quadro de inter-relações e suas intensidades já foi identificado em muitas pesquisas, tal como encontrado nesta. No entanto, de maneira um tanto original, os resultados desta pesquisa mostraram que, embora o efeito da coesão sobre o medo é fraco, quando a coesão social faz a mediação entre insegurança social e medo, a coesão anula quase totalmente o efeito da insegurança.

Esse impacto que ocorre no processo de mediação da coesão social, também ocorre quando a desorganização social é tida enquanto mediadora da relação entre insegurança e medo, porém, ao contrário da coesão, a desorganização amplifica o efeito da insegurança. No entanto, e isso chama a atenção, o poder mediador da coesão é muito maior que o da desorganização. Isso implica em direcionar atenção a um preditor clássico do medo do crime, a coesão social, porém não somente enquanto um preditor com uma relação direta importante, mas sim enquanto mediador de uma relação, na qual a coesão oferece uma capacidade notável de impactar no medo do crime de maneira indireta. Pensando em estudos futuros, reflete-se sobre quais outros preditores do medo a coesão teria capacidade de neutralizá-los ou apenas reduzi-los.

Em suma, esta tese chama a atenção para aspectos sociais que determinam o sentimento de medo do crime. A insegurança social, enquanto percepção de desprezo e ansiedade, mostrou-se um elemento de grande relevância no estudo do medo do crime de uma população, possibilitando inclusive ampliar as análises sobre indicadores e preditores clássicos de medo do crime, quando combinados à ideia de insegurança social. Em grande medida, as análises reverberam achados empíricos que apontam que muito do que se mensura como medo do crime é, na verdade, insegurança social “disfarçada”, de maneira que o medo do crime, por parecer algo objetivo, tangível, pode servir como uma esponja, absorvendo ansiedades sociais amplas e difusas em suas medidas. Academicamente, ainda há muito o que pesquisar visando ampliar o debate teórico e metodológico sobre o objeto desta tese, o medo do crime e seus fatores sociais correlatos.

Alguns problemas foram identificados e dizem respeito ao tamanho da amostra, que não alcançou o tamanho esperado (n=850), impactando na qualidade do processo de amostragem e portanto, de representação da população em estudo. O n de 626 teria sido o suficiente caso tivessem sido realizadas adequações na amostragem durante o processo de campo, visando melhor distribuir as entrevistas por bairros. Outra limitação diz respeito ao problema inerente às pesquisas de opinião do tipo “pesquisas de vitimização”, em desenho transversal *(cross-sectional),* registrando opiniões estáticas das pessoas em um determinado momento, como uma “fotografia” que representa um momento em um percurso temporal. Isso impacta especialmente em relação à medida de vitimização, em que os respondentes são convidados a lembrar de situações envolvendo crimes que ocorreram no passado recente, sem possibilitar qualquer inferência sobre o quanto as opiniões sobre os mesmos eventos podem variar no futuro. Ao mesmo tempo, não se considerou vitimizações possivelmente marcantes ocorridas há mais de um ano que podem continuar impactando as pessoas até hoje.

De forma original para o espaço em questão, a cidade de Florianópolis/SC, a pesquisa permitiu levantar informações que podem ser úteis e complementares para trabalhos de pesquisa futuros, além de ampliar o conhecimento a respeito das dinâmicas do medo do crime em território brasileiro. Nesse sentido, o estudo ofereceu um elemento para debate cientificamente embasado a respeito do sensível tema do medo do crime, mostrando como determinantes sociais podem ser importantes e até essenciais analiticamente, de maneira individual ou combinados a outras abordagens.

De maneira geral, a tese traz implicações teóricas ligadas à apresentação de mecanismos causais e seu impacto sobre o medo do crime. Mais especificamente, ao apresentar os mecanismos de ação da insegurança social sobre o medo do crime, com a mediação de aspectos socio contextuais em nível de bairro, tem-se um valioso elemento para exploração futura junto aos estudos de vitimização e MDC. Além disso, fora da *casca de noz* dos estudos ao MDC socialmente direcionados, a tese traz elementos acessórios para a reflexão e pesquisa futura sobre os usos e consequências políticas do MDC. Como apresentado, o MDC enquanto conceito científico nasceu como um produto científico e político, já que os objetivos dos estudos visavam definir e mensurar as percepções de medo e outras atitudes correlatas, visando possibilitar políticas de governo que interferissem nas taxas criminais e de medo do crime.

Os estudos de vitimização, os mesmos que integram questões sobre o medo do crime, são amplamente justificados por sua capacidade de refinar os dados de registros criminais oficiais, na medida em que permitem o cálculo das cifras ocultas (taxa de crimes não registrados oficialmente) ao confrontar os dados de pesquisa de vitimização com os dados oficiais de registros criminais. Por sua vez, levantamentos sistemáticos sobre o medo do crime, incluindo seus preditores clássicos e novos elementos tais a insegurança social e ansiedades sociais difusas, podem ser socialmente e politicamente justificados devido sua capacidade de abordar cientificamente o sensível fenômeno do medo do crime, de maneira a oferecer contrapontos às corriqueiras ideias e políticas que recorrem ao populismo penal e ao populismo autoritário sempre que possível, inclusive ao tratar a respeito da relação entre violência e medo do crime de maneira simplória, com objetivos exclusivamente políticos, e sem método científico.
