---
title: "Medo do crime e Insegurança"
subtitle: "Análise dos determinantes sociais do medo do crime em Florianópolis/SC"
---

## Apresentação {#apresentação}

Este site reúne os principais resultados do estudo Medo do crime e Insegurança: Análise dos determinantes sociais do medo do crime em Florianópolis/SC. O resumo do estudo pode ser lido abaixo, e nas abas laterais à esquerda é possível navegar pelas seções do trabalho. O trabalho é resultado da Tese de doutorado em Sociologia e Ciência Política do pesquisador Denis Berté Sálvia, sob orientação do professor Dr. Julian Borba.

## Resumo

Este trabalho volta-se à análise dos determinantes sociais do medo do crime (MDC) em Florianópolis, estado de Santa Catarina, no ano de 2019. O estudo envolveu mensurar relações entre medidas de medo do crime e seus preditores mais conhecidos: vitimização criminal, ambiente de bairro (desorganização e coesão social), e marcadores sociodemográficos de vulnerabilidade (sexo, idade, cor/raça), adicionando um elemento recente em pesquisas de medo do crime, especialmente no Brasil: a insegurança social. O conceito de insegurança social foi definido e operacionalizado enquanto um tipo de vulnerabilidade social ligada a dois elementos distintos, mas relacionados: a autopercepção de desprezo e exclusão social, e a ansiedade em relação à própria condição de saúde atual, financeira e de saúde no futuro breve. A questão subjacente do trabalho é: a insegurança social importa aos estudos do medo do crime? Especificamente, explorou-se a capacidade preditiva dos conceitos e os mecanismos pelos quais a insegurança social afeta o medo do crime, além de seu impacto direto. Os dados foram coletados através de survey com amostra representativa da população maior de 18 anos residente em Florianópolis, e o questionário foi aplicado entre novembro e dezembro de 2019. A base final saneada conta com 626 entrevistas que permitem mensurar a percepção de medo do crime da amostra. Foram implementadas técnicas de análise estatística multivariada, como análise de componentes principais com a finalidade de extração de fatores latentes, regressão linear múltipla, a fim de testar a capacidade preditiva dos conceitos, e modelagem de equações estruturais, que combina as duas técnicas anteriores e possibilitou verificar a robustez dos modelos de regressão, além de permitir testar caminhos teóricos pelos quais a insegurança social afeta o MDC. Os resultados apontam para a relevância do conceito de Insegurança Social, e reforçam achados presentes na literatura da área, demonstrando o impacto de indicadores de vitimização criminal, desorganização social e de vulnerabilidades sociodemográficas de gênero, idade e cor/raça sobre o medo do crime. Encontrou-se efeitos significativos da insegurança social sobre o medo do crime tanto de maneira direta quanto indireta, demonstrando como fatores sociais em contexto de bairro têm o potencial de elevar ou de neutralizar o impacto da insegurança social sobre o medo do crime. Ainda, os achados chamam atenção para a magnitude e significância dos efeitos das chamadas “ansiedades difusas” sobre o medo, demonstrando como ansiedades sociais de grande amplitude geram efeitos que recaem sobre as medidas de MDC.

Palavras-chave: Medo do crime. Insegurança social. Desorganização social. Coesão social. Vitimização criminal.
