---
title: Introdução
---

Esta pesquisa é direcionada a um objeto de estudo que pode parecer um tanto estranho, inusual à primeira vista. Afinal, o “medo do crime” (MDC) parece encerrar em si qualquer necessidade de questionamento ou reflexão que não seja ligada ao crime, ou à criminalidade. O próprio termo parece oferecer uma lógica para sua compreensão absoluta: o medo do crime. O medo do crime depende do crime, simples e diretamente. Mas, como qualquer objeto ou tema científico, as coisas não são tão simples e óbvias como os sentidos imediatos possam fazer parecer.

Com quase 60 anos de acúmulo de pesquisas teóricas e empíricas realizadas em muitos países, em diferentes áreas e disciplinas, o conjunto de estudos sobre esse “complicado” objeto de investigação se mostra atualmente bastante amplo e teoricamente diversificado. Não ao acaso, o foco inicial dos estudos estava ligado diretamente à criminalidade e seus efeitos sobre as percepções e atitudes das populações frente as mais diversas experiências criminais que as poderiam ter colocado em condições de vítimas (vitimização). Embora a história do medo do crime seja mais antiga, assim o campo de estudos começou, e essa relação direta entre crime e medo continua sendo verificada, de fato, em muitos estudos até hoje.

Não é difícil imaginar os impactos que um evento criminal, mais ou menos violento, mais ou menos recorrente, pode causar nas pessoas e nas suas relações com as demais. Da mesma maneira, esse impacto poderá perdurar por períodos variados. Para quem já foi vítima de algum crime essa reflexão se torna mais fácil, pois recorre-se à própria memória, a qual pode ser marcante em função de outros detalhes, como o tipo de crime, o grau de violência, se a vítima foi a própria pessoa ou alguém próximo, da família, ou mesmo um desconhecido que se ouviu falar pelas ruas do bairro ou na televisão/internet. O crime nos impacta, e um fato a ser considerado quando pensamos sobre a relação entre crime e medo aqui, no Brasil, na América Latina, o fazemos em locais com altas taxas criminais quando comparados a outros países ou regiões do mundo. Portanto, seria claramente justificada a expectativa de um quadro de mais ou maior medo distribuído entre toda população de um país ou região, um estado ou município. Mas, por mais contraditório que possa parecer, não é apenas o crime ou o envolvimento direto e/ou indireto com um evento criminal que pode explicar o medo do crime dos indivíduos e populações.

Estudos recentes concluíram que mesmo entre os países com taxas criminais decrescentes, baixíssimas quanto a alguns crimes em relação a países como o Brasil, o medo do crime chegou a patamares nunca alcançados antes (Dammert; Malone, 2003; Clarke, 2013; Dammert, 2012; Trindade; Durante, 2021). Países como o Chile, por exemplo, que concentra as taxas criminais mais baixas da América Latina, mas que a população exibe as maiores preocupações ligadas ao crime e criminalidade da região (Dammert; Tobar, 2018). Esse intrigante “paradoxo” é conhecido pelos pesquisadores ao tema, e as explicações variam. De forma geral, há décadas são reconhecidos outros fatores que parecem andar junto ao medo do crime, associados ou correlacionados de maneira que, quando observados, pode-se esperar e estimar a presença de maior ou menor medo. Originalmente, a principal preocupação, o principal elemento pensado em termos causais ou preditivos foi o crime em si, o ato de vitimização em suas variadas tipologias em foco. Mas logo os estudos passaram a explorar e mensurar fatores estruturais, ambientais, e/ou individuais que pareciam explicar o movimento das medidas de medo do crime, de maneira independente da criminalidade ou do fato das pessoas terem sido vítimas em dado período ou durante a vida toda (Hale, 1996).

Atualmente, o tema do MDC recebe atenção em muitos países e por diferentes áreas do conhecimento, especialmente nas ciências humanas e sociais como criminologia, psicologia, ciência política e sociologia. Os dados primários sobre o MDC são comumente levantados em estudos de vitimização e, como veremos no capítulo 2, isso acontece desde o começo da formação do campo de estudos do MDC. No Brasil muitas pesquisas sobre o medo do crime foram realizadas, a maior parte em nível municipal e sobretudo em capitais, e como parte integrante de pesquisas de vitimização. Em grande medida, a prática de se incluir questões sobre medo junto aos estudos de vitimização se deve ao fato de que os fenômenos não são, necessariamente, relacionados. Em 2021, o Instituto Brasileiro de Geografia e Estatística (IBGE) inseriu um bloco temático sobre “sentimento de insegurança”, na Pesquisa Nacional por Amostra de Domicílios Contínua Anual (PNADC/A), contemplando muitos indicadores clássicos para mensuração da insegurança em relação ao crime e quanto a outros aspectos. No entanto, os dados disponíveis são agregados em nível de país ou grande região (IBGE, 2021).

Com o intuito de investigar as percepções sobre o medo do crime da população de uma capital brasileira, este estudo envolveu a realização de uma pesquisa de vitimização e medo do crime junto à uma amostra representativa da população maior de idade da cidade, no ano de 2019. Não foram encontrados dados ou publicações com resultados de pesquisas sobre o medo do crime e seus principais preditores no município de Florianópolis, Santa Catarina, com exceção de uma pesquisa com amostragem estadual, que realizou 172 entrevistas sobre o tema na cidade (Santos Júnior, Dutra; Silva Filho, 2007). Considerando a crescente atenção direcionada a estudos de vitimização e de medo do crime em cidades brasileiras, esta tese reuniu um conjunto de dados que mensuram a percepção de medo do crime de uma amostra da população da cidade.

A base final contou com 626 entrevistas, as quais foram analisadas de maneira a avaliar os principais determinantes do MDC, levando em consideração os preditores “clássicos” do medo do crime, e incorporando ao estudo uma noção e abordagem mais recente aos determinantes do medo, a “insegurança social” (Valente; Pertegas; 2018; Valente; Pertegas; Olmos, 2019). Nesta pesquisa, adicionar o elemento da “insegurança social” ao estudo do medo ofereceu um caráter desafiador, já que incorporou um tema ligado ao medo do crime que ainda é pouco estudado no Brasil. Além disso, possibilitou explorar, de maneira indireta, o conhecimento sobre as “ansiedades difusas” ou “medo expressivo”, no sentido em que visou-se definir e mensurar uma possível expressão desse fenômeno, ligada ao sentimento de ansiedade financeira e de saúde em relação ao futuro, e à percepção de exclusão social. Em tese, tem-se que fatores envolvendo desorganização e coesão social, vitimização e vulnerabilidades sociodemográficas podem afetar, em distintos graus, o medo do crime.

No entanto, cabe indagar se fatores pouco considerados nas pesquisas, como a insegurança social, poderiam produzir resultados semelhantes. O modelo de insegurança social em relação ao MDC traz elementos teóricos e empíricos importantes ao debate e foi pouco trabalhado no Brasil. O pano de fundo da tese envolve apurar possíveis mecanismos pelos quais os componentes de insegurança social utilizados afetam as medidas de medo do crime. A questão subjacente a ser respondida é: a insegurança social importa aos estudos do medo do crime? E algumas questões guiaram a etapa empírica do estudo: O modelo de insegurança social pode ser um preditor do medo? Como é a relação entre as medidas utilizadas de insegurança social e MDC? Como as medidas de insegurança social afetarão o medo em cada um de seus elementos? Em que medida os componentes da variável insegurança social poderiam ser considerados como expressões daquilo que na literatura do MDC é tratado como “ansiedade difusa”? A insegurança social desempenha efeitos indiretos com os outros aspectos explicativos do medo? Seu efeito é direto ou mediado por outras variáveis?

Desta forma, esta tese é estruturada incluindo, no subtópico 1.1, os objetivos da pesquisa e as hipóteses a serem testadas, encerrando a Introdução da tese. Depois, o capítulo 2 inicia com um balanço teórico envolvendo as noções de medo, risco e insegurança em teorias sociológicas contemporâneas (subtópico 2.1), e algumas das teorias apresentadas voltam ao trabalho no capítulo de discussão dos resultados. Ainda no capítulo 2, apresenta-se a gênese dos estudos sobre medo do crime (subtópico 2.2), em seguida trata-se das diferentes definições, formas de mensuração e as múltiplas abordagens ao MDC (subtópicos 2.3 e 2.4). O capítulo 2 é encerrado com a apresentação do contexto de realização do estudo, incluindo um levantamento e discussão de pesquisas realizadas em capitais brasileiras (subtópicos 2.5). Em seguida, no capítulo 3, Metodologia, são apresentados detalhes metodológicos que envolveram o desenho da pesquisa, incluindo a estrutura teórico-metodológica, metodologia do questionário, da amostragem e coleta de dados, do processo de análise e operacionalização das variáveis, e das análises multivariadas implementadas. No capítulo 4, Análises e Discussão, são apresentados e discutidos os resultados das análises realizadas para os testes das hipóteses de pesquisa. Por fim, no capítulo 5, Conclusão, consta uma discussão conclusiva restrita aos objetivos e hipóteses de tese.

1.1 OBJETIVOS E HIPÓTESES

Esta pesquisa analisou o medo do crime de uma amostra da população de Florianópolis/SC, integrando ao estudo um elemento não recente, mas pouco usual sobre as possíveis explicações desse objeto de estudo, a “insegurança social” (Valente; Pertegas, 2018). A insegurança social, por sua vez, é operacionalizada enquanto uma medida de vulnerabilidade social ampliada, composta por duas noções distintas mas relacionadas de vulnerabilidade: desprezo social, representado por situações em que as pessoas percebem que são desprezadas pelas outras em função de seu local de moradia ou condição econômica, e sentem-se como se estivessem excluídos da sociedade. A outra noção é a ansiedade sobre o futuro, representada por situações em que as pessoas expressam pessimismo sobre a própria condição financeira e de saúde no futuro breve, além de uma autoavaliação negativa sobre a condição atual de saúde. O objetivo subjacente da tese foi verificar se a insegurança social, tal como caracterizada nesta pesquisa, é um conceito importante para os estudos do MDC. De maneira específica, a pesquisa envolveu verificar se duas facetas distintas, mas relacionadas à insegurança social têm capacidade explicativa sobre o medo do crime. Primeiramente, verificando a magnitude da insegurança social enquanto um preditor do medo e, depois, investigando de que maneira a insegurança social afeta o MDC de maneira direta e indireta, através da combinação com outros elementos já conhecidos nos estudos teóricos e empíricos anteriores. Neste sentido, a pesquisa não deixou de considerar fatores importantes presentes no campo de estudos do tema, como a vitimização criminal, desorganização e coesão social, e aspectos sociodemográficos. A estrutura da tese envolveu verificar a significância e mensurar a magnitude com a qual os componentes de insegurança social utilizados afetam as medidas desagregadas de medo do crime, em cada uma de suas dimensões elementares consideradas (emocional, cognitiva, comportamental). Em seguida, verificar se essas relações ocorrem de maneira direta ou indireta, revelando a mediação de aspectos ambientais na definição dos caminhos e do impacto da insegurança sobre o medo. A questão subjacente da tese é: a insegurança social importa aos estudos do medo do crime?

As seguintes hipóteses nortearam o estudo quanto ao objetivo geral e específicos: H1: a insegurança social afeta o medo do crime, servindo como preditor relevante; H2: a insegurança social terá efeitos distintos sobre cada um dos elementos do MDC; H3: a insegurança social afeta a dimensão “afetiva” do medo em maior grau, reforçando o argumento da insegurança enquanto “ansiedade difusa”; H4: os três elementos do MDC têm relações recíprocas, sendo preditores uns dos outros; H5: o efeito da insegurança social sobre o MDC segue caminhos distintos, sendo mediado por aspectos ambientais de vizinhança; H6: a insegurança social exerce efeito direto sobre o MDC; H7: a desorganização social (desordens estruturais e incivilidades no bairro) media a relação entre insegurança e medo, amplificando sua magnitude; H8: a coesão social media a relação entre insegurança e medo, reduzindo seu impacto.

Em suma, espera-se encontrar evidências que corroborem para a aceitação de todas as hipóteses investigadas. Para analisar os dados foram empregadas técnicas de análise estatística multivariada. As hipóteses 1 a 4 foram testadas através de análise de regressão linear múltipla, e as hipóteses 5 a 8, através de modelos de equações estruturais. No capítulo 4 as discussões intercambiam os resultados de maneira a discuti-los conjuntamente.
