---
title: "Metodologia"
---

Para analisar a relação entre medo do crime e insegurança social de uma amostra da população adulta residente em Florianópolis/SC, este estudo apoiou-se em metodologia de *survey*. Foram realizadas 626 entrevistam que integram a base de dados final, e todo o trabalho de coleta de dados em campo se deu entre 19/11/2019 e 16/12/2019. Neste capítulo serão apresentados detalhes metodológicos que envolvem o desenho da pesquisa, incluindo, nessa ordem: metodologia do questionário, da amostragem e coleta de dados; do processo de análise e operacionalização das variáveis; e das análises multivariadas. Em termos gerais, trata-se de uma pesquisa quantitativa orientada pela metodologia de *survey*, com amostragem probabilística de característica interseccional, e os dados coletados foram analisados através de técnicas multivariadas de análise. 

Conforme já apontado, esta pesquisa analisou o medo do crime de uma amostra da população de Florianópolis/SC, integrando ao estudo um elemento não tão recente, mas pouco usual sobre as possíveis explicações do medo do crime no Brasil e que, neste estudo, foi tratado como uma medida de “insegurança social” (Valente; Pertegas, 2018). A estrutura da tese envolveu verificar a significância e mensurar a magnitude com a qual os componentes de insegurança social utilizados afetam as medidas desagregadas de medo do crime, em cada uma de suas dimensões elementares (emocional, cognitiva, comportamental). Em seguida, verificar se essas relações ocorrem de maneira direta ou indireta, revelando a mediação de aspectos ambientais na definição dos caminhos e no impacto da insegurança sobre o medo. Espera-se ao final deste capítulo ter apontado em detalhes de que maneira isso foi realizado empiricamente.

## QUESTIONÁRIO

O questionário utilizado foi adaptado de um instrumento já validado (Valente; Lanna; Chainey, 2019). Esse instrumento foi produzido com a finalidade de oferecer uma nova concepção de *survey* para estudos sobre vitimização, e foi construído em duas etapas: primeiro, foram analisados os questionários de cinco estudos nacionais sobre crime e vitimização de cinco países da União Europeia (UE), o que serviu para identificar maneiras de aumentar a consistência de algumas medidas comuns dos questionários, incluindo uma série de novas variáveis independentes com vistas a observação a relação entre medo do crime e alguns indicadores sociológicos. Os *surveys* analisados foram: *Crime Survey for England and Wales* (Reino Unido); *Sicurezza dei cittadini* (Itália); *Cadre de vie et sécurité* (França); *Encuesta de Seguridad Pública de Cataluña* (Espanha); *Victims and Opinion Research* (Hungria).

Na segunda etapa foi desenvolvido um painel *Delphi* envolvendo doze especialistas em pesquisas ligadas à criminalidade, o que serviu para melhorar o desenho do novo questionário, contemplando elementos individuais, sociais e espaciais da insegurança (Valente; Lanna; Chainey, 2019). O resultado foi um questionário nomeado MARGIN *Questionnaire on Perception of Insecurity*, que foi traduzido em 6 línguas, não incluindo o português. Como já informado, o questionário utilizado para a pesquisa empírica desta tese é uma adaptação com pequenas mudanças no questionário acima citado, e a tradução para o português foi realizada pelo autor (ver o questionário no Apêndice A).

### Pré-teste e teste-piloto

Antes do início do trabalho de coleta de entrevistas em campo foi realizado um pré-teste com o objetivo de testar o software de coleta utilizado^[\[1\]](#_ftn1)^, verificar a aplicação das questões e avaliar algumas medidas de tempo de aplicação. Como pré-teste foram realizadas entrevistas com o questionário final, e a equipe de coleta testou entre si e com outras pessoas. Os dados resultantes foram armazenados em base própria para que se pudesse realizar análises descritivas. Nenhuma alteração no desenho da amostra ou no questionário foi realizada a partir do pré-teste, mas ganhou-se experiência com o instrumento de coleta. A base de dados do pré-teste contou com cerca de 15 casos e foi descartada.

Após o pré-teste realizou-se o teste-piloto em campo. Definiu-se que seriam necessárias 45 entrevistas (5% do tamanho da amostra prevista inicialmente), que deveriam ser realizadas em locais diferentes, levando no máximo dois dias de campo. Ao final do segundo dia foram realizadas 49 entrevistas as quais serviram como base de dados do piloto. Após discussão e análise parcial dos dados coletados, foram feitas algumas alterações no questionário, mudanças na amostra no que diz respeito à coleta, e traçadas estratégias para cumprir o campo no período esperado. Abaixo constam as alterações no questionário a partir da avaliação proporcionada pelo teste-piloto (as alterações na amostragem e no processo de coleta de campo serão apresentadas após a subseção correspondente):

a\. A palavra ‘preocupação’ (questão 8) gerou certa confusão para muitos entrevistados, e foi alterada pela palavra ‘problema’ (o “quanto você se preocupa”, passou a “o quanto isso é um problema para você”), resultando em um sentido mais objetivo e concreto da pergunta, comum em pesquisas de vitimização (Skogan, 2012);

b\. Foi adicionado ‘tentativa de roubo’ e ‘tentativa de furto’, assim como ‘crime virtual’ na lista de crimes a serem abordados;

c\. No final do questionário foi adicionada uma questão solicitando o endereço da pessoa, em especial nome de bairro e rua. Isso servirá para eventual mapeamento da distribuição das entrevistas por bairros, embora a amostra não permita análises comparativas agregadas em nível de bairro;

d\. Foi adicionado ‘curso técnico ou tecnólogo’ na questão da escolaridade. Isso serviu para controlar melhor as cotas de escolaridade;

e\. Na questão sobre ‘com quem mora’ foi adicionada a opção ‘mora com pais e filhos menores de idade’. Antes havia apenas a opção ‘mora com esposa/marido e filhos’. Isso permitiu focar com maior exatidão a população que mora com filhos menores de idade, variável de possível interesse;

f\. Entrevistadores foram orientados a realizar uma pergunta aberta sobre a ‘opinião pessoal a respeito do tema’ de maneira que estimulasse os entrevistados a responderem, seguindo a recomendação de um entrevistador experiente. A intenção era informar que aquela seria a última pergunta, demonstrando que não havia pressa para se receber a resposta. O resultado é que muitas pessoas se sentiram à vontade para emitir opinião pessoal geral, melhorando os resultados dessa questão aberta, discursiva. O resultado das análises dessa questão não integraram diretamente este estudo, mas estão disponíveis no Apêndice H.

## COLETA DE DADOS E AMOSTRAGEM

A coleta de dados foi realizada através de entrevistas face a face (método *Computer Assisted Personal Interviewing* (CAPI), com questionário programado em tablets ou celulares, com softwareespecífico para pesquisas com *survey*. O software opera sem a necessidade de conexão com internet, registrando os dados em tempo real, inclusive a localização geográfica de cada entrevista em um mapa, sua duração/horário de início e fim, etc. A duração média das entrevistas foi de 12 minutos, e os entrevistadores utilizaram crachás de estudantes da Universidade Federal de Santa Catarina (UFSC) para facilitar a abordagem e apresentação aos respondentes.

A equipe foi composta de dois entrevistadores, e em apenas um dia mais uma pessoa foi designada para o campo, nos demais, apenas dois. A ampla maioria das entrevistas foi realizada por uma pessoa com anos de experiência em entrevista de pesquisas de opinião de cunho sociopolítico e mercadológico. Definiu-se previamente que a coleta deveria ser realizada em até 30 dias corridos a partir do primeiro dia.

Quanto à amostragem, serão apresentadas as características gerais, o plano amostral e, em seguida, as alterações realizadas no plano amostral após o teste-piloto.

### Características da amostragem

A população em estudo são os habitantes de Florianópolis maiores de 18 anos de idade. Os elementos de pesquisa, ou unidades de análise, portanto, foram os domiciliados permanentes maiores de 18 anos, que residiam há pelo menos um ano na cidade.

São duas unidades de amostra: primária, sendo os setores censitários; secundária, sendo os residentes permanentes nos setores respectivos, maiores de 18 anos. Para produzir a moldura de amostragem utilizou-se a lista dos setores censitários, estratificados por número de domiciliados permanentes maiores de 18 anos (IBGE, 2010), conforme apresentado a seguir.

### Plano amostral

Realizou-se uma amostragem probabilística, representativa da população em estudo, com um desenho de Amostragem de Probabilidade Proporcional ao Tamanho (PPT) (Babbie, 2003). Definiu-se o total de 850 entrevistas como o tamanho ideal da amostra. O nível de confiança preliminarmente estimado foi de 95% e a margem de erro máxima estimada, considerando um modelo de amostragem aleatório simples, foi de 3,5% sobre os resultados encontrados no total da amostra. A seguir apresentam-se detalhes metodológicos do plano com número de entrevistas esperadas de 850, no entanto, a base final saneada conta com 626 entrevistas, com maior margem de erro (4%).

A amostragem foi elaborada em dois estágios. Primeiro, todos os setores censitários foram listados, em ordem decrescente, de acordo com o número de residentes permanentes maiores de 18 anos. Na base de dados do Censo 2010, em Sinopse por Setores, as variáveis selecionadas que serviram como parâmetros para estratificação e seleção foram: Número de pessoas residentes em domicílio particular permanente, por setor (V017); Número de Moradores Maiores de 18 anos (V50 até V72) (IBGE, 2010). Isso visou a homogeneização dos estratos para posterior extração/sorteio, sendo que, dentro de cada estrato, cada setor deveria ter a mesma probabilidade de ser sorteado^[\[2\]](#_ftn2)^.

Sendo a lista composta por 591 setores, e um total de 315.157 residentes maiores de 18 anos, foi preciso extrair 170 setores para a amostra^[\[3\]](#_ftn3)^, sendo realizadas cinco entrevistas em cada setor, resultando no final em 850 entrevistas (170\*5=850). Foi então necessário estratificar a lista em 85 partes iguais, sendo que de cada estrato seriam extraídos dois setores (85\*2=170).

No entanto, existem setores que são muito grandes em comparação com outros, o que exige que sua representação seja maior (Babbie, 2003, p. 167). Definiu-se então que os setores que tivessem 900 ou mais pessoas seriam listados e extraídos à parte. Esses setores foram no total 41 (6,9% do total de setores), sendo habitados por 43.118 pessoas (14% do total de habitantes maiores de 18 da cidade da cidade) (IBGE, 2010). A fração total de amostragem foi de 0,0027 (850/315.157=0,0027). Assim, multiplicou-se o total de moradores dos grandes setores por essa fração (43.118\*0,0027), o que resultou em 116 (decidiu-se subir o número para 125, por questão de arredondamento). Isso significa que 125 entrevistas deveriam ser realizadas nesses setores grandes, exigindo a extração de 25 setores dessa lista de 41 (61% de probabilidade de cada setor ser sorteado). Restou extrair outros 145 setores do restante da lista de 550 (que corresponderam a 725 entrevistas).

Foram criados 73 estratos com o restante da lista de 550 setores. Não foi possível deixar todos os estratos do mesmo tamanho, e o primeiro estrato era de 7 setores, o segundo de 8, o terceiro de 7, e o quarto de 8, e assim sucessivamente. De cada um desses estratos foram sorteados/extraídos 2 setores, sendo que a probabilidade de seleção de cada setor dentro de cada estrato, de 7 ou 8, era de 28% e 25%, respectivamente. O último estrato da lista, por ser formado por setores pequenos em número de residentes, ficou com um total de 10 setores, do qual foram extraídos 2, sendo a probabilidade de 20% de cada setor desse estrato ser sorteado.

No segundo estágio, dentro dos setores sorteados, os respondentes foram selecionados através de cotas amostrais proporcionais. De acordo com as características da população, realizou-se controle de cotas sociodemográficas quanto a sexo, idade, cor/raça, grau de instrução e nível econômico dos entrevistados.

No Apêndice B são apresentadas as tabelas 9 a 12, com cotas sociodemográficas previstas e realizadas em campo, e no Apêndice C, as tabelas 13 a 17 apresentam o número de entrevistas esperadas e realizadas por bairro, estratificadas por 5 regiões da cidade.

### Alterações na amostragem e coleta resultantes do estudo-piloto

Foram identificados alguns problemas e realizadas algumas alterações durante o piloto que dizem respeito a questões do questionário, as quais já foram apresentadas anteriormente. Os problemas mais significativos foram referentes à amostragem e coleta. O plano amostral considerava que em cada setor sorteado seriam realizadas cinco entrevistas, em cinco domicílios diferentes, evitando realizar mais de uma entrevista com moradores de uma mesma rua (Babbie, 2003; Beato, 2010).

A ideia inicial era ‘circular’ em cada setor de maneira que as entrevistas fossem realizadas uma distante das outras. Logo no início verificou-se a dificuldade em seguir com as coletas em domicílios dentro dos setores sorteados, sem extrapolar o período de referência do trabalho de campo. Muitas vezes foi difícil encontrar pessoas em casa, já que muitas pessoas se ausentam da residência no período do dia. Com a equipe disponível, que era de 2 a 3 pessoas, seria impossível alcançar o número de entrevistas desejado no prazo de 30 dias.

Logo durante o piloto ficou claro que fazer as entrevistas somente em domicílios seria algo difícil de cumprir com uma equipe pequena. A ausência de pessoas em casa em alguns setores, o tempo gasto caminhando entre ruas, e as pessoas que não queriam responder foram alguns empecilhos encontrados. Além disso, nas ruas o pesquisador está exposto às intempéries do tempo/clima, o que dificulta uma previsibilidade acurada no número de coletas diárias possíveis de se fazer.

Assim, decidiu-se por realizar as entrevistas não apenas nas residências, mas também em locais de circulação dentro de cada bairro, abordando os transeuntes nesses locais, de preferência próximo aos setores sorteados, e anotando o endereço de moradia de cada entrevistado. Dessa maneira foi possível manter o filtro principal, que se tratava de morar em Florianópolis há pelo menos um ano (12 meses), mantendo o controle do número de entrevistas esperadas por bairro. Em alguns lugares, como no bairro Centro ou Trindade, era comum o respondente não residir naquele bairro.

Mesmo assim a entrevista era realizada e o endereço de moradia registrado para controlar o número de entrevistas por bairro, seguindo a amostragem. As entrevistas não eram realizadas quando a pessoa era menor de 18 anos, residia há menos de um ano na cidade, residia em outras cidade, ou simplesmente se recusava a participar. Foi possível controlar o número de entrevistas por bairro, mantendo o controle de cotas sociodemográficas.

## PROCESSO DE ANÁLISE E OPERACIONALIZAÇÃO DAS VARIÁVEIS EM ESTUDO

A seguir, são descritos detalhes sobre a estratégia analítica e operacionalização das variáveis dependentes e preditoras.As medidas de medo e suas variáveis explicativas produzidas não são originais entre os estudos já realizados no país, porém, foram incorporadas novas variáveis preditoras, trazendo à discussão uma definição de insegurança social e, de maneira indireta, aspectos como “medo expressivo” e “ansiedades difusas” (Farrall; Gray; Jackson, 2009). Neste trabalho, a insegurança social foi explorada enquanto fenômeno que potencialmente afeta as medidas de medo do crime, e enquanto um fator que caracteriza em algum grau aspectos da “ansiedade difusa”.

A análise foi dividida em duas etapas principais que envolveram modelos de regressão múltipla e de equações estruturais. Primeiro, para mensurar o medo do crime, este foi decomposto em três dimensões básicas, emocional, cognitiva e comportamental. Além dos construtos que caracterizam a desorganização, coesão, e insegurança social, foram utilizadas variáveis para mensurar os efeitos da vulnerabilidade sociodemográfica e da vitimização sobre cada uma das três medidas elementares de medo do crime. Ao mesmo tempo, verificou-se a ocorrência de efeitos recíprocos entre os três elementos do MDC.

A segunda etapa envolveu testar o ajuste de três modelos de equações estruturais: um modelo teoricamente baseado em Valente, Pertegas e Olmos (2019), outro em Natal e Oliveira (2021), e um terceiro que foi produzido reunindo elementos teóricos dos dois anteriores. Na segunda etapa explorou-se o efeito direto da medida de insegurança social sobre os componentes do MDC, assim como o efeito direto sobre a variável latente MDC, e os efeitos indiretos com mediação das variáveis coesão social e desorganização social. Os detalhes estão na próxima seção.

**Processo de análise**

A estratégia de análise baseou-se em Natal e Oliveira (2021) e foi dividida em duas etapas principais. A Etapa 1 envolveu testar individualmente cada elemento do medo (emocional, cognitivo e comportamental) enquanto variável dependente frente aos conjuntos de variáveis explicativas, e frente aos demais elementos para verificar efeitos autônomos e recíprocos do MDC.

Isso foi realizado através de uma série de regressões múltiplas em que os conjuntos de variáveis independentes foram inseridos passo a passo, possibilitando a observação dos efeitos de cada uma, incluindo a insegurança social, sobre cada elemento do MDC. Como o estudo envolveu testar a relação de reciprocidade entre os elementos do medo, eles foram inseridos nos modelos também como variáveis preditoras. Essa etapa testou os enunciados e permitiu responder à H1, H2, H3 e H4.

Seguindo, a Etapa 2 envolveu a utilização Modelagem de Equações Estruturais (MEE), em que foi analisado mais detalhadamente o efeito dos preditores sobre as variáveis dependentes, possibilitando avaliar as diferenças observadas em relação à Etapa 1, e então foi possível avaliar o quanto os três modelos teóricos se ajustam aos dados desta pesquisa.

De acordo com Natal e Oliveira (2021, p.769):

A opção pelo uso da MEE se deve a vários motivos, entre os quais destacamos a verificação da validade de hipóteses complexas, propiciada pela estimação simultânea de mais de uma variável dependente e pela análise de caminhos, que possibilita o exame dos efeitos diretos e indiretos de variáveis explicativas sobre variáveis dependentes (Gau, 2010; Neves, 2018).

Assim, foi possível avaliar a magnitude e a significância estatística dos modelos que testam o efeito da insegurança social em relação ao MDC, revelando os mecanismos pelos quais a insegurança atua indiretamente sobre o medo. Essa etapa respondeu as hipóteses H5 a H8.

### Operacionalização das variáveis

A seguir, apresenta-se a operacionalização dos principais indicadores utilizados como variáveis dependentes e preditoras. As tabelas com a descrição das variáveis para cada análise são apresentadas no Capítulo 4, Análises e Discussão.

**Variáveis dependentes - Medo do crime em três dimensões elementares e enquanto um construto**

Neste estudo, para a etapa de análise através de regressões múltiplas, adaptou-se os construtos teórico-metodológicos de Rodrigues e Oliveira (2012) e de Natal e Oliveira (2021), que por sua vez buscou reproduzir os estudos de Rader (2004, 2007), o qual considera o medo em seus elementos afetivo, cognitivo e comportamental. Em Natal e Oliveira (2021), cada um desses elementos foi tratado como variável dependente, os elementos emocional e cognitivo foram construídos a partir de análise fatorial, e o elemento comportamental através da construção de um índice e posterior padronização *zscore.* Aqui reside uma diferença na construção empírica dos modelos de regressão, considerando que em nosso estudo as três variáveis dependentes, referentes aos três elementos do medo, são mensuradas através das suas variáveis originais, normalizadas através da técnica de Box-Cox para a análise de regressão (Box; Cox, 1964; Fávero; Belfiore, 2022), e mantida no formato original (likert 1 a 10) para a equação estrutural.

A variável dependente MDC emocional foi construída a partir de uma variável que já foi utilizada como medida de medo do crime em muitos estudos internacionais e no Brasil (Borges; Cano, 2021; Rodrigues; Oliveira, 2012; Valente; Pertegas; Olmos, 2019). Em Rodrigues e Oliveira (2012) a pergunta que caracteriza o elemento emocional do medo questiona *o quão seguras* as pessoas se sentem ao andar nas ruas do bairro sozinhas, de dia e à noite. Porém, em Natal e Oliveira (2021), uma questão quase idêntica mensura um componente do aspecto cognitivo do medo, pois questiona a *frequência* que as pessoas se sentem seguras ao andar sozinhas nas ruas do bairro.

Em nosso estudo, o MDC emocional/afetivo é mensurado em escala likert de 1 a 10, e pergunta o seguinte: “O quão seguro(a) você se sente ao andar sozinho(a) pelo bairro à noite? Por favor, classifique de 1 (nada seguro) a 10 (muito seguro)”. A ordem da variável original foi invertida para ter o mesmo sentido que as outras duas a seguir, ficando uma medida crescente de insegurança: 1 (muito seguro) a 10 (muito inseguro).

O elemento cognitivo do MDC também é caracterizado por uma variável mensurada originalmente em escala likert de 1 a 10. Como apontado, o elemento cognitivo considera uma avaliação que envolve frequência ou probabilidade, uma avaliação cognitiva. A questão era a seguinte: “Com que frequência você se sente inseguro(a) em seu bairro? Por favor, classifique de 1 (nunca) a 10 (com muita frequência)”.

A dimensão comportamental do MDC é mensurada através de uma questão do mesmo formato que as duas anteriores, numa escala de 1 a 10. Essa dimensão envolve atitudes em relação ao medo, e geralmente essas atitudes são preventivas ou defensivas (Rader *et al.*, 2007). A questão utilizada foi: “Com que frequência você muda seus planos e/ou sua rotina para evitar situações que fazem você se sentir inseguro no bairro onde mora? Por favor, classifique de 1 (nunca) a 10 (com muita frequência)”.

As três variáveis originais são ligeiramente assimétricas, e nenhuma passou no teste de normalidade de distribuição dos resíduos (*Shapiro-Francia*) enquanto variável dependente. Por esta razão realizou-se a normalização *Box-Cox* de maneira a aproximar a distribuição dos resíduos à normalidade, validando a especificação dos modelos lineares. Os códigos em linguagem R e os resultados dos testes dos pressupostos dos modelos lineares para as três variáveis dependentes estão no Apêndice E.

**Variáveis preditoras: insegurança social, desorganização, coesão, vitimização e vulnerabilidades sociodemográficas**

Para os modelos de regressão foram criados quatro variáveis latentes através de análise fatorial por componentes principais. A análise validou 4 fatores, nomeados desorganização, coesão, ansiedade, e exclusão, os quais são mensurados em *zscore*. As demais variáveis preditoras são as originais, porém em formato *dummy*. Segue mais detalhes sobre as variáveis.

**Insegurança Social**

A operacionalização da Insegurança Social foi adaptada de Valente e Pertegas (2018) e Valente, Pertegas e Olmos (2019). Para a regressão, ela é mensurada através de dois construtos latentes, duas subdimensões criadas via análise fatorial pelo método análise de componentes principais. Para a MEE, previu-se a criação dos mesmos dois construtos, além de um construto de segunda ordem formado pelas duas subdimensões latentes.

Um dos fatores latentes diz respeito à autopercepção de exclusão social, e foi composto por quatro questões, mensuradas em escala likert de 1 a 10 (alfa de Cronbach’s: 0,678):

“Em que medida você concorda ou discorda das seguintes afirmações? Por favor, classifique de 1 (discordo totalmente) a 10 (concordo totalmente)”.

a.             algumas pessoas me olham com desprezo devido minha renda ou atividade de trabalho

b.             algumas pessoas me olham com desprezo devido ao lugar onde moro

c.             algumas pessoas me olham com desprezo devido a minha cor da pele ou etnia

d.             eu me sinto deixado de fora da sociedade

O outro construto diz respeito à ansiedade em relação ao futuro e avaliação da saúde pessoal, e foi composto por três questões (alfa de Cronbach’s: 0,635). A seguir, os três itens utilizados para caracterizar a ansiedade de saúde e financeira em relação ao futuro próximo e avaliação de saúde pessoal:

“Em que medida você concorda ou discorda das seguintes afirmações? Por favor, classifique de 1 (discordo totalmente) a 10 (concordo totalmente)”.

a.              eu acho que minha saúde pode piorar nos próximos 12 meses

b.              eu acho que minha situação financeira pode piorar nos próximos 12 meses

c.              Como você avalia seu estado geral de saúde? Por favor, classifique de 1 (muito bem) a 10 (muito mal).

Segue uma explanação sobre a dimensão teórico empírica da construção da insegurança social (Valente;Pertegas, 2018, p. 165):

These two sub-dimensions are conceived as a comprehensive means of enabling an analysis of both future-oriented worries and actual social conditions. On the one hand, expectations regarding personal wellbeing and good health are pre-conditions for the use and enjoyment of urban spaces. Health outcomes and financial status have been proven to be strongly interlinked and pessimistic views about their evolution could engender “status anxiety” and, in turn, negatively affect on people's social participation. Similarly, makes the case that insecurity is really about the threat of losing something (e.g. your health or socio-economic status) in the future \[...\].

São esses dois construtos e suas variáveis correspondentes que caracterizam a insegurança social nos modelos desenvolvidos nesta tese. Na MEE, o modelo prevê um construto de segunda ordem.

**Desorganização Social - variável contextual sobre a comunidade de bairro**

A medida de desorganização social também foi criada a partir de análise fatorial e foi mensurada pela padronização Z dos escores fatoriais. O fator final conta com cinco itens de resposta (alfa de Cronbach’s: 0,752). A questão é:

“Agora eu vou citar alguns problemas que podem ou não ocorrer em seu bairro, e gostaria de saber sua avaliação quanto a isso. Por favor dê uma nota de 1 (se não chega a ser um problema) até 10 (é um problema muito importante):

a.              pobreza e dificuldades econômicas entre os moradores (item removido)

b.             tráfico de drogas e outras atividades ilegais em espaços públicos

c.              você, ou alguém próximo a você, ser vítima de algum crime no bairro

d.             comportamentos antissociais (como pessoas fazendo muito barulho, bêbadas ou usando drogas, sujando o espaço público etc.)

e.              falta de infraestrutura (falta de serviços de saúde, educação, transporte, lazer etc.)

f.               más condições dos equipamentos urbanos (de iluminação, das ruas ou calçadas, casas deterioradas, carros abandonados, lixo nas ruas ou terrenos, etc.)

O item ‘a’ foi removido para melhor adequação do modelo, considerando que a variável apresentou comunalidade abaixo do valor mínimo esperado. Como o item foi excluído na análise fatorial, também não foi incluído nas análises de regressão e equações estruturais.

**Coesão Social - variável contextual sobre a comunidade de bairro**

A coesão social é tratada como um subconjunto teórico dentro do quadro da desorganização social, porém é esperado que ela tenha um sentido inverso ao da percepção de desordens e incivilidades. Enquanto os elementos da desorganização podem aumentar o medo, a coesão pode fazê-lo diminuir. Essa variável foi o quarto construto via análise fatorial e composta de três variáveis que exploraram relações de confiança e auxílio entre as pessoas na vizinhança, além da satisfação de se viver onde se vive. Foram três questões em escala likert de 1 a 10 (alfa de Cronbach’s: 0,643):

“Você discorda ou concorda com as seguintes afirmações a respeito de seu bairro? Por favor, dê uma nota de 1 (se você discorda totalmente) até 10 (se concorda totalmente).”

a.             eu gosto de morar em meu bairro

b.             nós moradores nos relacionamos bem neste bairro

c.             frente a uma situação difícil ou perigosa, eu posso conseguir ajuda na vizinhança

**Vitimização criminal**

A questão sobre vitimização criminal questionava se as pessoas haviam sido vítimas de algum crime pessoalmente, ou tiveram alguém próximo que foi vítima nos últimos 12 meses que antecederam a pesquisa. A questão foi a seguinte:

“Nos últimos 12 meses, você ou alguém próximo a você foi vítima de algum crime?”

0\. Não

1\. Sim, eu fui vítima de algum crime.

2\. Sim, alguém próximo a mim foi vítima de algum crime.

3\. Sim, tanto eu quanto alguém que conheço fomos vítimas de algum crime.

99\. Não sei/Não respondeu.

Devido ao número de respostas não foi possível separar, nos modelos utilizados, as vítimas diretas das vicárias. Além disso, não foi possível separar os crimes contra propriedade dos contra a pessoa, ou com violência. Portanto, para caracterizar o contato recente com a vitimização criminal, as respostas 1, 2 e 3 foram agregadas, resultando em uma nova variável que mensurou a soma da vitimização de si, vicária, e dupla, respectivamente, em formato binário (dummy), separando quem foi ou não vítima.

Assim, a medida agregou vítimas pessoais, vicárias e duplas nos 12 meses antecedentes ao estudo, dos seguintes crimes contra a pessoa e contra a propriedade:

1\. Arrombamento e invasão da residência, com furto/roubo de algo;

2 Tentativa de arrombamento da residência;

3\. Furto de objeto pessoal (carteira, telefone, notebook, etc.);

4\. Roubo de objeto pessoal (assalto, com violência);

5\. Furto de veículo;

6\. Furto de algo de dentro do veículo;

7.Roubo de veículo;

8\. Vandalismo e danos criminais contra sua propriedade (carro, casa, empresa etc);

9\. Crime virtual (golpe/fraude pelo celular/internet, etc.);

10.Golpe ou fraude (clonagem de cartão de crédito, dinheiro falso, etc.);

11\. Ameaças (de morte ou de agressão física);

12\. Agressão física (marcar em caso de ‘tentativa de homicídio’);

13\. Assédio sexual (agressão verbal ou física de ímpeto sexual);

14\. Estupro ou tentativa de estupro;

15\. Discriminação (de qualquer natureza);

16\. Sequestro;

18\. Tentativa de roubo ou furto.

**Vulnerabilidades sociodemográficas**

As variáveis do conjunto vulnerabilidades sociodemográficas abordaram marcadores de cor/raça, idade, sexo/gênero, escolaridade e renda pessoal ou familiar, com algumas transformações das variáveis originais visando a construção de variáveis binárias (*dummy)*. A cor/raça foi recodificada em duas categorias (não branca, branca), a idade foi recodificada em duas categorias, mais velhos e mais novos. Essa divisão foi realizada a partir de uma avaliação da média (40 anos) e da mediana (37 anos) da variável, sendo que 58% dos casos têm até 40 anos de idade. Assim, pessoas de 18 a 40 anos compuseram o grupo mais novo, e pessoas com 41 ou mais anos de idade formaram o grupo de mais velhos.

O sexo foi recodificado em uma variável binária (feminino, masculino), a escolaridade foi recodificada em duas categorias, baixa, para quem concluiu até o ensino médio, e alta, para quem concluiu ensino superior, pós-graduação, ou ensino técnico. A variável renda também foi transformada em binária, de baixa a média renda, e de média a alta renda. No primeiro grupo pessoas ou famílias com renda mensal de menos de 880,00 reais, até 4.500,00 reais. No segundo, de 4.501,00 a mais de 18.000,00 reais mensais. No entanto, por razão de adequação dos modelos as variáveis de renda e escolaridade não foram utilizadas nas análises multivariadas.

## TÉCNICAS DE ANÁLISE MULTIVARIADA

A seguir apresentam-se alguns apontamentos gerais de maneira resumida sobre as técnicas utilizadas referentes às etapas 1 e 2 do processo de análise.

### Análise fatorial por componentes principais (ACP)

Essa técnica de análise multivariada foi utilizada com a finalidade de redução de dados, permitindo a criação de variáveis índices que sintetizam as medidas de uma série de variáveis em construtos que, por sua vez, representam dimensões latentes na estrutura de dados original.

A análise por componentes principais é uma técnica de interdependência e permite que se determine um novo conjunto de variáveis (fatores) a partir de um conjunto de variáveis originais linearmente correlacionadas (redução estrutural). Pode ser útil para verificar a validade de construtos, para elaborar rankings, e para a extração de fatores ortogonais para posterior uso em análises multivariadas que necessitem de ausência de multicolinearidade, como análises de regressão múltipla ou logística (Fávero; Belfiore, 2022; Matos; Rodrigues, 2019).

O planejamento envolve verificar a adequabilidade da base de dados, determinar a técnica de extração e o número de fatores a serem extraídos e decidir o tipo de rotação dos fatores (Figueiredo Filho; Silva Júnior, 2010). Quanto à matriz de correlações entre as variáveis, a maior parte dos coeficientes devem ter valores maiores que 0,30 (Figueiredo Filho *et al.*, 2014).

Para verificar a adequação global da análise fatorial, avalia-se a estatística *Kaiser-Meyer-Olkin* (KMO) e o teste de esfericidade de *Bartlett*. A estatística KMO fornece a proporção de variância considerada comum a todas as variáveis na amostra em análise (inércia). Essa estatística varia entre 0 (zero) e 1 (um), e quanto mais variância compartilhada, mais próximo de 1 (um) é o KMO. Pode-se considerar que valores de 0,50 ou mais validam, em diferentes graus de aceitação, a adequação global da análise fatorial, sendo inaceitáveis abaixo de 0,50 (Fávero; Belfiore, 2022, p. 386; Hair *et al.,* 2009, p. 110).

O teste de esfericidade de Bartlett é um teste para verificar a presença de correlações entre as variáveis, e permite verificar se o valor da estatística X²Bartlett (qui-quadrado de Bartlett) é maior que o valor crítico da estatística. O teste fornece a significância estatística de que a matriz de correlação tem correlações significantes entre pelo menos algumas das variáveis, portanto, o teste deve apresentar um p-valor menor que 0,05 (5%) (Hair *et al.,* 2009).

Em resumo, o primeiro estágio da ACP envolve verificar o tamanho da amostra, sendo o mínimo entre 50 e 100 casos; a maior parte dos coeficientes de correlação devem apresentar valores acima de 0,30; O valor do teste KMO deve ser no mínimo 0,50; e o valor de p do teste BTS deve ser menor que 5% (Figueiredo Filho; Silva Júnior, 2010).

Após isso, no segundo estágio deve ser determinada a técnica de extração de fatores a ser utilizada. Nesta pesquisa utilizou-se o método por componentes principais. Para definir o número de fatores a serem extraídos utilizou-se a regra do *eigenvalue,* ou critério de Kaiser, que determina que sejam extraídos apenas fatores com *eigenvalue* acima de 1 (um). Pode-se, de maneira auxiliar, fazer uso da avaliação gráfica do *Scree test*, e o critério da variância acumulada para determinar o número de fatores a serem extraídos.

Em seguida, deve-se escolher o método matemático de rotação dos fatores no espaço geométrico, rotação ortogonal ou oblíqua. A rotação ortogonal Varimax é comumente utilizada e procura minimizar o número de variáveis que apresentam altas cargas em cada fator. A variância acumulada pelos fatores deve ser de preferência maior que 60% (Figueiredo Filho; Silva Júnior, 2010).

A seguir apresenta-se brevemente a técnica de regressão múltipla que, assim como a anterior, é apresentada de maneira simplificada, orientada ao que foi realizado neste estudo. Os códigos utilizados em linguagem R e o resumo dos testes de pressupostos das variáveis construídas por análise fatorial estão no Apêndice D. A descrição das variáveis construídas é apresentada no Capítulo 4.

### Modelo de regressão linear múltipla

A análise de regressão múltipla é uma técnica estatística de dependência, amplamente utilizada para analisar a relação entre uma única variável dependente (critério) e várias variáveis independentes (preditoras). Pode ser considerada uma extensão da regressão linear simples por permitir no mesmo modelo a inclusão de mais de uma variável independente. O objetivo da análise de regressão múltipla é usar as variáveis independentes, cujos valores são conhecidos, para prever os valores da variável dependente selecionada pelo pesquisador (Hair *et al.,*2009). Um critério a ser cumprido na escolha de um modelo de regressão múltipla é que a variável dependente deve ser métrica (quantitativa, contínua ou discreta), e as independentes devem ser métricas, ou *dummies,* especialmente quando se trata de variáveis qualitativas categóricas (Chein, 2019; Fávero; Belfiore, 2022).

O modelo geral de regressão linear pode ser assim definido:

Yi = α +*b*1.X1i + *b*2.X2i + ⋯ + *b*n.Xni + µi

Onde:

Y = a variável dependente quantitativa;

α = o intercepto (*Alpha*, constante ou coeficiente linear);

*b =* os coeficientes de cada variável (*Beta*, coeficientes angulares);

X = as variáveis independentes;

µ = o termo de erro ou resíduo (diferença entre o valor real de Y e o valor previsto no modelo);

*i =* cada uma das observações da amostra;

Embora existam diferentes métodos para estimar os parâmetros de um modelo de regressão linear múltipla, para este trabalho é importante apresentar os pressupostos dos modelos de regressão por Mínimos Quadrados Ordinários (MQO). O método dos MQO segue dois critérios gerais: a soma dos erros é igual a zero, e a soma dos erros ao quadrado será a menor possível (Fávero; Belfiore, 2022).

O primeiro pressuposto a verificar foi a normalidade dos resíduos, o que pressupõe que os resíduos apresentem distribuição normal. A violação desse pressuposto invalida os resultados do *valor-P* dos testes *t* e do teste *F.* Para verificar esse pressuposto pode ser utilizado o teste de Shapiro-Wilk para amostras pequenas ou o teste de Shapiro-Francia, para amostras moderadas a grandes (n \> 500).

O segundo pressuposto é sobre a multicolinearidade, o qual considera que não existem correlações elevadas entre as variáveis independentes, e que existem mais observações que variáveis independentes. A violação desse pressuposto é chamada de multicolinearidade. Para verificar pode ser realizada uma matriz de correlações simples, assim como avaliado o Determinante da matriz (X’X), e avaliados os valores de VIF (*Variance Inflation Factor*) e de *Tolerance*.

O terceiro pressuposto aponta que os resíduos (µ) não devem estar correlacionados com qualquer variável independente. Isso significa que a distribuição da variância dos resíduos deve ser constante sobre a variável independente. A violação desse pressuposto leva à heterocedasticidade. Para verificação podem ser aplicados testes de *Breusch-Pagan* e *Cook-Weisberg*. Por fim, um quarto pressuposto espera que os resíduos sejam aleatórios e independentes, ou seja, não estejam auto correlacionados. Para verificação pode ser realizado testes de *Durbin-Watson* e de *Breusch-Godfrey* (Fávero; Belfiore, 2022). Todos os códigos utilizados em linguagem R e os resultados dos testes de pressupostos das regressões lineares estão no Apêndice E.

### Modelagem de equações estruturais

A Modelagem de Equações Estruturais (MEE) é uma técnica multivariada mais complexa e que possibilita avançar o potencial exploratório e preditivo oferecido pelas técnicas de interdependência e dependência apresentadas anteriormente. Há uma amplitude enorme de usos dessa técnica, que combina usos da análise fatorial e da análise de regressão múltipla, permitindo testar modelos que operam com muitas relações de dependência, incluindo variáveis latentes e observáveis, ao mesmo tempo. O modelo de medição é utilizado para especificar a mensuração de variáveis latentes através das variáveis observáveis, e um modelo estrutural detalha as relações entre as variáveis latentes.

De acordo com Hair *et al*., (2009, p. 543):

Modelagem de equações estruturais (SEM) é uma família de modelos estatísticos que buscam explicar as relações entre múltiplas variáveis. Fazendo isso, ela examina a estrutura de inter-relações expressas em uma série de equações, semelhante a uma série de equações de regressão múltipla. Tais equações descrevem todas as relações entre construtos (as variáveis dependentes e independentes) envolvidos na análise. Construtos são inobserváveis ou fatores latentes representados por múltiplas variáveis (como variáveis representando um fator em análise fatorial).

Para verificar como o modelo teórico se ajusta aos dados observados são utilizados alguns índices de ajuste. Índices de ajuste absoluto refletem o quão bem o modelo reproduz os dados observados sem comparar a um modelo alternativo. É importante verificar o p-valor do teste Qui-quadrado, que mede a diferença entre a matriz de covariância observada e a estimada pelo modelo, portanto, espera-se que o p-valor do teste Qui-quadrado seja igual ou maior que 5% (0,05), indicando que não há diferença significativa. Quanto à estimativa do teste, espera-se que seja a menor possível. O *Standardized Root Mean Square Residual* (SRMR) informa sobre a média das diferenças entre valores observados e previstos, sendo esperados valores menores que 0,08 para um bom ajuste. Outro índice de ajuste absoluto é o *Root Mean Square Error of Approximation* (RMSEA), o qual avalia o ajuste considerando o número de parâmetros estimados. Valores menores que 0,06 sugerem um bom ajuste (Hair, 2009; Kline, 2023).

Além dos índices de ajuste absolutos, também é importante observar os índices relativos. O *Comparative Fit Index* (CFI) compara o ajuste do modelo testado com um modelo nulo, e valores acima de 0,90 indicam um bom ajuste, e acima de 0,95 excelente. O *Tucker-Lewis Index* (TLI) avalia o ajuste considerando o número de parâmetros incluídos no modelo, e valores acima de 0,90 indicam bom ajuste.

Outros índices são utilizados para comparar modelos alternativos, considerando a complexidade dos modelos. Aqueles com um número elevado de parâmetros adicionados e sem melhora no ajuste são penalizados, por isso os menores valores indicam o melhor ajuste, com maior parcimônia. Podem ser verificados os valores de *Akaike Information Criterion* (AIC) e o *Bayesian Information Criterion* (BIC) (Hair, *et al.,* 2009; Kline, 2023).

Essas foram apenas algumas medidas de ajuste entre as várias existentes, pois foram as utilizadas para avaliar o ajuste da etapa MEE desta pesquisa, mas o tipo de ajuste pode variar dependendo da demanda analítica do pesquisador. Hair *et al.* (2009) chama a atenção, criticamente, para esta etapa crucial da análise:

O principal objetivo de qualquer um desses índices de ajuste é auxiliar o pesquisador na discriminação entre modelos especificados aceitáveis e inaceitáveis. A questão crucial ainda permanece: o que indica um bom ajuste para esses índices? Periódicos especializados estão repletos com resultados SEM que citam um valor de 0,90 para índices importantes, como TFI, CFI, NFI ou GFI, como indicando um modelo aceitável. Alguns podem citar precedentes de um artigo previamente publicado. Outras vezes, a regra do 0,90 é simplesmente citada como uma regra ad hoc razoável sem suporte de teoria prévia. Em geral, de alguma forma o 0,90 se tornou o número mágico para modelos bem ajustados (Hair *et al.*, 2009, tradução nossa, p 572).

De toda forma, ao verificar os ajustes dos modelos desta pesquisa foram utilizados os índices e testes indicados acima, para três modelos de equações estruturais diferentes, mas com algumas semelhanças tanto nos modelos de medição quanto nos estruturais. Para discutir os resultados, no capítulo 4 serão apresentados os diagramas de caminhos, ilustrações gráficas que explicitam as significâncias e magnitudes das relações de dependência e interdependência entre as variáveis e construtos. Os códigos em linguagem R e os resultados integrais dos modelos de equações estruturais estão no Apêndice F.

^[\[1\]](#_ftnref1)^ Ver em: <https://www.datagoal.com.br/>. Acesso em: 9 out. 2024.

^[\[2\]](#_ftnref2)^ Detalhes do trabalho com a base de dados da sinopse por setores do Censo 2010, para a amostra:

Aplica-se filtro deixando apenas o município de Florianópolis/SC, o qual tem um total de 639 setores. Filtra-se de maneira a deixar visível apenas setores em situação urbana (códigos 1 - Área urbanizada de cidade ou vila, 2 - Área não-urbanizada de cidade ou vila, 3 - Área urbana isolada), tem-se um total de 599 setores. Os setores excluídos são referentes às áreas em situação rural (códigos 4, 5, 6, 7 e 8, sendo: 4 - Aglomerado rural de extensão urbana; 5 - Aglomerado rural isolado – povoado; 6 - Aglomerado rural isolado – núcleo; 7 - Aglomerado rural isolado - outros aglomerados; 8 - Zona rural, exclusive aglomerado rural). A principal razão da exclusão dos setores em situação rural se dá pelo fato do foco da pesquisa ser o ambiente urbano em suas particularidades. Além desses, setores marcados com ‘X’ na base (dados nulos ou positivos, omitidos por proteção ao informante, segundo o IBGE) também foram excluídos (Total de 8 setores com ‘X’ nas duas variáveis, V017 e V50 até V72, sendo: 2 no ribeirão da ilha, 1 na agronômica, 4 no centro, e 1 na cachoeira bom jesus). O resultado é uma lista com 591 setores, referente à região insular e continental da cidade de Florianópolis.

[\[3\]](#_ftnref3) É uma convenção comum na teoria de amostragem que 5 entrevistas são suficientes para representar um “quarteirão de recenseamento” (Babbie, 2003, p. 166).
